"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ÓÇ∂](color_light_purple)\
$os\
[ÓÇº](bg:color_bg0 fg:color_light_purple)\
$directory\
[ÓÇº](bg:color_bg1 fg:color_bg0)\
$git_branch\
$git_status\
[ÓÇº](fg:color_bg1)\
$line_break$character"""

palette = 'dark'

[palettes.dark]
color_fg0 = '#3b4261'
color_fg1 = '#c0caf5'
color_fg2 = '#000000'
color_fg3 = '#8289a8'
color_bg0 = '#292e42'
color_bg1 = '#1a1d2b'
color_orange = '#ff9e64'
color_light_purple = '#c5c3e3'
color_purple = '#9d7cd8'
color_red = '#ff007c'
color_yellow = '#ffc777'

[os]
disabled = false
style = "bg:color_light_purple fg:color_fg2"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "Û∞åΩ"
Gentoo = " Û∞£® "
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "üí©"
Artix = "Û∞£á"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"

[username]
show_always = true
style_user = "bg:color_bg0 fg:color_fg1"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
home_symbol = "ÔÄï  ~"
style = "fg:color_light_purple bg:color_bg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[git_branch]
symbol = "Ôêò"
style = "bg:color_bg1"
format = '[[ $symbol $branch ](fg:color_fg3 bg:color_bg1)]($style)'

[git_status]
style =	"fg:color_fg3 bg:color_bg1"
format = '[$all_status$ahead_behind ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[‚ù≠](fg:#337e6f)'
error_symbol = '[‚ù≠](fg:color_red)'
vimcmd_symbol = '[‚ù≠](fg:#337e6f)'
vimcmd_replace_one_symbol = '[‚ù≠](fg:color_purple)'
vimcmd_replace_symbol = '[‚ù≠](fg:color_purple)'
vimcmd_visual_symbol = '[‚ù≠](fg:color_yellow)'
